//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumMessage
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int TopicId { get; set; }
        public string Body { get; set; }
        public string IdParentMessage { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Tag { get; set; }
        public string UserId { get; set; }
    
        public virtual ForumTopic Topic { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
