//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumTopic
    {
        public ForumTopic()
        {
            this.ForumMessages = new HashSet<ForumMessage>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int ForumCategoryId { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UserId { get; set; }
    
        public virtual ForumCategory ForumCategory { get; set; }
        public virtual ICollection<ForumMessage> ForumMessages { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
